Fix

diff --git a/.github/workflows/apply-label.yaml b/.github/workflows/apply-label.yaml
--- a/.github/workflows/apply-label.yaml
+++ b/.github/workflows/apply-label.yaml
@@ -2,18 +2,15 @@ name: apply-label
 
 on:
   pull_request:
-    types: [labeled]
+    types: [labeled, unlabeled]
 
 jobs:
 
   deploy:
-    name: Process command
+    name: Deploy
     runs-on: ubuntu-latest
     
-    if: github.event.action.labeled && equals(github.event.label.name, 'deploy')
-    
-    env:
-      TF_VERSION: 0.12.26
+    if: github.event.action.labeled && github.event.label.name =='deploy'
 
     steps:
 
@@ -25,10 +22,26 @@ jobs:
           echo ::set-env name=ENVIRONMENT ::$(echo ${GITHUB_BASE_REF} | cut -d'/' -f3)
           echo ::set-env name=REGION      ::$(echo ${GITHUB_BASE_REF} | cut -d'/' -f4)
 
-      - name: Check
+      - name: Verify
         run: |
-          printenv
+          echo "Deployed to ${PLATFORM}/${ENVIRONMENT}/${REGION}!"
 
-          echo "${{ toJson(github) }}"
-          echo "---"
-          echo "${{ toJson(env) }}"
+  rollback:
+    name: Rollback
+    runs-on: ubuntu-latest
+    
+    if: github.event.action.unlabeled && github.event.label.name =='deploy'
+
+    steps:
+
+      - name: Setup
+        run: |
+          if [[ ! "${GITHUB_BASE_REF}" =~ ^env\/.* ]]; then >&2 echo "error"; exit 1; fi
+
+          echo ::set-env name=PLATFORM    ::$(echo ${GITHUB_BASE_REF} | cut -d'/' -f2)
+          echo ::set-env name=ENVIRONMENT ::$(echo ${GITHUB_BASE_REF} | cut -d'/' -f3)
+          echo ::set-env name=REGION      ::$(echo ${GITHUB_BASE_REF} | cut -d'/' -f4)
+
+      - name: Verify
+        run: |
+          echo "Rolled back from ${PLATFORM}/${ENVIRONMENT}/${REGION}!"
