Fix apply-label

diff --git a/.github/workflows/apply-label.yaml b/.github/workflows/apply-label.yaml
--- a/.github/workflows/apply-label.yaml
+++ b/.github/workflows/apply-label.yaml
@@ -14,6 +14,13 @@ jobs:
 
     steps:
 
+      - name: Setup
+        run: |
+          if [[ ${GITHUB_BASE_REF} =~ ^env\/.* ]]; then >&2 echo "error"; exit 1; fi
+
+          echo ::set-env name=PLATFORM::    $(echo ${GITHUB_BASE_REF} | cut -d'/' -f3)
+          echo ::set-env name=ENVIRONMENT:: $(echo ${GITHUB_BASE_REF} | cut -d'/' -f4)
+          echo ::set-env name=REGION::      $(echo ${GITHUB_BASE_REF} | cut -d'/' -f5)
 
       - name: Check
         run: |
@@ -22,11 +29,4 @@ jobs:
           echo "${{ toJson(github) }}"
           echo "---"
           echo "${{ toJson(env) }}"
-
-      - name: Setup
-        run: |
-          if [[ ${GITHUB_BASE_REF} =~ ^env\/.* ]]; then >&2 echo "error"; exit 1; fi
-
-          echo ::set-env name=PLATFORM::    $(echo ${GITHUB_BASE_REF} | cut -d'/' -f3)
-          echo ::set-env name=ENVIRONMENT:: $(echo ${GITHUB_BASE_REF} | cut -d'/' -f4)
-          echo ::set-env name=REGION::      $(echo ${GITHUB_BASE_REF} | cut -d'/' -f5)
+          
