Fix

diff --git a/.github/workflows/apply-label.yaml b/.github/workflows/apply-label.yaml
--- a/.github/workflows/apply-label.yaml
+++ b/.github/workflows/apply-label.yaml
@@ -6,9 +6,23 @@ on:
 
 jobs:
 
-  prep:
+  check:
     runs-on: ubuntu-latest
     steps:
+      - name: print
+        run: |
+          printenv
+          echo ${{ github }}}
+          echo ${{ env }}
+
+  deploy:
+    name: Deploy
+    runs-on: ubuntu-latest
+    
+    if: github.event.action == 'labeled' && github.event.label.name =='deploy'
+
+    steps:
+
       - name: Setup
         run: |
           if [[ ! "${GITHUB_BASE_REF}" =~ ^env\/.* ]]; then >&2 echo "error"; exit 1; fi
@@ -17,20 +31,26 @@ jobs:
           echo ::set-env name=ENVIRONMENT ::$(echo ${GITHUB_BASE_REF} | cut -d'/' -f3)
           echo ::set-env name=REGION      ::$(echo ${GITHUB_BASE_REF} | cut -d'/' -f4)
 
-  deploy:
-    needs: prep
-    runs-on: ubuntu-latest
-    if: github.event.label.name == 'deploy'
-    steps:
       - name: Verify
         run: |
           echo "Deployed to ${PLATFORM}/${ENVIRONMENT}/${REGION}!"
 
   rollback:
-    needs: prep
+    name: Rollback
     runs-on: ubuntu-latest
-    if: github.event.label.name == 'deploy'
+    
+    if: github.event.action == 'unlabeled' && github.event.label.name =='deploy'
+
     steps:
+
+      - name: Setup
+        run: |
+          if [[ ! "${GITHUB_BASE_REF}" =~ ^env\/.* ]]; then >&2 echo "error"; exit 1; fi
+
+          echo ::set-env name=PLATFORM    ::$(echo ${GITHUB_BASE_REF} | cut -d'/' -f2)
+          echo ::set-env name=ENVIRONMENT ::$(echo ${GITHUB_BASE_REF} | cut -d'/' -f3)
+          echo ::set-env name=REGION      ::$(echo ${GITHUB_BASE_REF} | cut -d'/' -f4)
+
       - name: Verify
         run: |
           echo "Rolled back from ${PLATFORM}/${ENVIRONMENT}/${REGION}!"
